// Temporary stub for backward compatibility
// These will be removed in future refactoring

export enum StatusCode {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  VALIDATION_ERROR = 422,
  INTERNAL_ERROR = 500,
  INVALID_CREDENTIALS = 1001,
  TOKEN_EXPIRED = 1002,
  INVALID_REFRESH_TOKEN = 1003,
  USER_NOT_VERIFIED = 1004,
  USERNAME_ALREADY_EXISTS = 1005,
  EMAIL_ALREADY_EXISTS = 1006,
  ACCOUNT_NOT_ACTIVE = 1007,
  USER_NOT_FOUND = 1008,
  INVALID_TOKEN = 1009,
  REFRESH_TOKEN_EXPIRED = 1010,
  REFRESH_TOKEN_REVOKED = 1011,
  INSUFFICIENT_PERMISSIONS = 1012,
  ROLE_ALREADY_ASSIGNED = 1100,
  ROLE_NOT_ASSIGNED = 1101,
  ROLE_IN_USE = 1102,
  USER_INACTIVE = 1103,
  MENU_HAS_CHILDREN = 1200,
  MENU_ALREADY_ASSIGNED = 1201,
  MENU_IN_USE = 1202,
  INVALID_PARENT_MENU = 1203,
}

export const StatusMessages: Record<StatusCode, string> = {
  [StatusCode.SUCCESS]: 'Success',
  [StatusCode.CREATED]: 'Created successfully',
  [StatusCode.BAD_REQUEST]: 'Bad request',
  [StatusCode.UNAUTHORIZED]: 'Unauthorized',
  [StatusCode.FORBIDDEN]: 'Forbidden',
  [StatusCode.NOT_FOUND]: 'Resource not found',
  [StatusCode.CONFLICT]: 'Resource already exists',
  [StatusCode.VALIDATION_ERROR]: 'Validation failed',
  [StatusCode.INTERNAL_ERROR]: 'Internal server error',
  [StatusCode.INVALID_CREDENTIALS]: 'Invalid credentials',
  [StatusCode.TOKEN_EXPIRED]: 'Token expired',
  [StatusCode.INVALID_REFRESH_TOKEN]: 'Invalid refresh token',
  [StatusCode.USER_NOT_VERIFIED]: 'User not verified',
  [StatusCode.USERNAME_ALREADY_EXISTS]: 'Username already exists',
  [StatusCode.EMAIL_ALREADY_EXISTS]: 'Email already exists',
  [StatusCode.ACCOUNT_NOT_ACTIVE]: 'Account is not active',
  [StatusCode.USER_NOT_FOUND]: 'User not found',
  [StatusCode.INVALID_TOKEN]: 'Invalid token',
  [StatusCode.REFRESH_TOKEN_EXPIRED]: 'Refresh token has expired',
  [StatusCode.REFRESH_TOKEN_REVOKED]: 'Refresh token has been revoked',
  [StatusCode.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  [StatusCode.ROLE_ALREADY_ASSIGNED]: 'Role already assigned',
  [StatusCode.ROLE_NOT_ASSIGNED]: 'Role not assigned',
  [StatusCode.ROLE_IN_USE]: 'Role is in use',
  [StatusCode.USER_INACTIVE]: 'User is inactive',
  [StatusCode.MENU_HAS_CHILDREN]: 'Cannot delete menu with children',
  [StatusCode.MENU_ALREADY_ASSIGNED]: 'Menu already assigned',
  [StatusCode.MENU_IN_USE]: 'Menu is in use',
  [StatusCode.INVALID_PARENT_MENU]: 'Invalid parent menu',
};
